[package]
name = "profile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "profilelib"
path = "src/lib.rs"

[dependencies]
tonic = "0.12.0"
prost = "0.13.1"
tokio = { version = "1.38.0", features = ["full"] }
clap = { version = "4.5.9", features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
idgen = {path="../../libs/idgen"}
thiserror = "1.0.62"
serde = { version = "1.0.204", features = ["derive"] }
# redis = { version = "0.23.0", features = ["tokio-comp"] }
serde_json = "1.0.120"
regex = "1.10.5"

[build-dependencies]
tonic-build = "0.12.0"
